branch-defaults:
  default:
    environment: null
    group_suffix: null
  main:
    environment: null
    group_suffix: null
global:
  application_name: django-project
  branch: null
  default_ec2_keyname: sai-keypair
  default_platform: Python 3.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
